//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Learning_WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Learning-WCF", ConfigurationName="Learning_WCF.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Learning-WCF/IStockService/Response", ReplyAction="Learning-WCF/IStockService/ResponseResponse")]
        string Response(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="Learning-WCF/IStockService/Response", ReplyAction="Learning-WCF/IStockService/ResponseResponse")]
        System.Threading.Tasks.Task<string> ResponseAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : Client.Learning_WCF.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<Client.Learning_WCF.IStockService>, Client.Learning_WCF.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Response(string client) {
            return base.Channel.Response(client);
        }
        
        public System.Threading.Tasks.Task<string> ResponseAsync(string client) {
            return base.Channel.ResponseAsync(client);
        }
    }
}
